### ISSUE TITLE
How to get to strong inside .dfn

### ISSUE THREAD

**Issue by Juliebou** [Juliebou/use-all-the-selectors#1]
@hellachella

I don't know how to get to the strong tag:

Use an adjacent selector to get the strong inside .dfn, the strong that starts “Botanically…”
— add color: #fff;

This is what I have: 
.wrapper .dfn:nth-child(2) p:nth-child(2) + strong {
  color: #fff;
}

**Comment by hellachella** [comment]
Looks like this was solved.
